"""Generates the four agent-readiness artifacts from a ProductAnalysis."""

from __future__ import annotations

from urllib.parse import urlparse

from models import Artifacts, AuditBreakdown, AuditScore, ProductAnalysis

AUTO_GENERATED_NOTE = (
    "This file was auto-generated by AgentReady and requires human review."
)

SCORE_POINTS = {
    "has_api": 20,
    "has_openapi_spec": 20,
    "has_llms_txt": 15,
    "has_structured_docs": 15,
    "has_api_key_auth": 15,
    "has_webhook_support": 15,
}


def generate_artifacts(analysis: ProductAnalysis, website_url: str | None) -> Artifacts:
    """Generate all four output files as strings from the structured LLM analysis."""
    return Artifacts(
        llms_txt=_generate_llms_txt(analysis, website_url),
        audit_md=_generate_audit_md(analysis),
        mcp_server_ts=_generate_mcp_server(analysis),
        openapi_yaml=_generate_openapi_yaml(analysis, website_url),
    )


def compute_audit_score(analysis: ProductAnalysis) -> AuditScore:
    """Score the product's agent-readiness out of 100 using the fixed rubric."""
    breakdown = AuditBreakdown(
        has_api=bool(analysis.core_actions),
        has_openapi_spec=analysis.has_existing_openapi,
        has_llms_txt=False,
        has_structured_docs=analysis.has_existing_docs,
        has_api_key_auth=analysis.auth_method == "api_key",
        has_webhook_support=analysis.webhook_support,
    )
    score = sum(points for check, points in SCORE_POINTS.items() if getattr(breakdown, check))
    return AuditScore(total=100, score=score, breakdown=breakdown)


def _generate_llms_txt(analysis: ProductAnalysis, website_url: str | None) -> str:
    lines = [
        f"# {analysis.product_name}",
        "",
        f"> {analysis.product_description}",
        "",
        f"Category: {analysis.product_category}",
        "",
        "## Key Actions",
    ]

    if analysis.core_actions:
        for action in analysis.core_actions:
            method = action.http_method if action.http_method != "UNKNOWN" else "?"
            endpoint = action.endpoint if action.endpoint != "UNKNOWN" else "(endpoint unknown)"
            lines.append(f"- {action.name}: {method} {endpoint} — {action.description}")
    else:
        lines.append("- No specific actions were detected. Add route-level docs for agents.")

    lines += [
        "",
        "## Authentication",
        f"Method: {analysis.auth_method}",
    ]

    if website_url:
        lines += ["", "## Links", f"Docs / Website: {website_url}"]

    lines += ["", "## Tech Stack", ", ".join(analysis.tech_stack) or "Not detected"]

    return "\n".join(lines) + "\n"


def _generate_audit_md(analysis: ProductAnalysis) -> str:
    score = compute_audit_score(analysis)
    breakdown = score.breakdown

    def check_line(label: str, passed: bool, points: int) -> str:
        icon = "✅" if passed else "❌"
        return f"- {icon} **{label}** ({points} pts)"

    checks = [
        check_line("Has a public API", breakdown.has_api, SCORE_POINTS["has_api"]),
        check_line(
            "Has an OpenAPI/Swagger spec", breakdown.has_openapi_spec, SCORE_POINTS["has_openapi_spec"]
        ),
        check_line("Has llms.txt", breakdown.has_llms_txt, SCORE_POINTS["has_llms_txt"]),
        check_line(
            "Has structured docs", breakdown.has_structured_docs, SCORE_POINTS["has_structured_docs"]
        ),
        check_line(
            "Has API key / token auth", breakdown.has_api_key_auth, SCORE_POINTS["has_api_key_auth"]
        ),
        check_line(
            "Has webhook support", breakdown.has_webhook_support, SCORE_POINTS["has_webhook_support"]
        ),
    ]

    working = [c for c in checks if "✅" in c] or ["- Nothing scored yet — this product is early-stage for agents."]
    missing = analysis.missing_agent_features or ["No specific gaps were identified."]
    recommendations = analysis.recommendations or ["No specific recommendations were generated."]
    priority = recommendations[:3]

    lines = [
        "# Agent-Readiness Audit",
        "",
        f"**Score: {score.score} / {score.total}**",
        "",
        "## What's Working",
        *working,
        "",
        "## What's Missing",
        *[f"- {item}" for item in missing],
        "",
        "## Action Items",
        *[f"{i}. {item}" for i, item in enumerate(recommendations, start=1)],
        "",
        "## Priority Fixes",
        *[f"{i}. {item}" for i, item in enumerate(priority, start=1)],
        "",
        "---",
        f"*{AUTO_GENERATED_NOTE}*",
    ]

    return "\n".join(lines) + "\n"


def _generate_mcp_server(analysis: ProductAnalysis) -> str:
    tools_ts = []
    for action in analysis.core_actions:
        tools_ts.append(
            f"""  server.tool(
    "{action.name}",
    "{_escape(action.description)}",
    {{
      // TODO: define input schema fields for {action.endpoint}
    }},
    async (input) => {{
      // TODO: implement — {action.http_method} {action.endpoint}
      throw new Error("Not implemented");
    }}
  );"""
        )

    tools_block = "\n\n".join(tools_ts) if tools_ts else "  // TODO: no actions were detected — add tools manually"

    return f"""/**
 * {analysis.product_name} — MCP Server Scaffold
 *
 * {AUTO_GENERATED_NOTE}
 *
 * Install:
 *   npm install @modelcontextprotocol/sdk
 *
 * Run:
 *   npx tsx mcp_server.ts
 */

import {{ Server }} from "@modelcontextprotocol/sdk/server/index.js";
import {{ StdioServerTransport }} from "@modelcontextprotocol/sdk/server/stdio.js";

const server = new Server(
  {{ name: "{_slug(analysis.product_name)}", version: "0.1.0" }},
  {{ capabilities: {{ tools: {{}} }} }}
);

// Auth: {analysis.auth_method}
// TODO: wire up authentication for outgoing requests to the real API.

{tools_block}

const transport = new StdioServerTransport();
await server.connect(transport);
"""


def _generate_openapi_yaml(analysis: ProductAnalysis, website_url: str | None) -> str:
    server_url = _server_url(website_url)

    paths_lines = []
    for action in analysis.core_actions:
        endpoint = action.endpoint if action.endpoint != "UNKNOWN" else "/unknown"
        method = action.http_method.lower() if action.http_method != "UNKNOWN" else "get"
        paths_lines.append(
            f"""  {endpoint}:
    {method}:
      summary: {_escape(action.description)}
      x-inferred: true
      responses:
        '200':
          description: Successful response"""
        )

    paths_block = "\n".join(paths_lines) if paths_lines else "  {}"

    return f"""# ⚠️ This spec was auto-generated and requires human review
openapi: 3.0.0
info:
  title: {analysis.product_name}
  description: {_escape(analysis.product_description)}
  version: 0.1.0
servers:
  - url: {server_url}
paths:
{paths_block}
"""


def _server_url(website_url: str | None) -> str:
    if not website_url:
        return "https://api.example.com"
    parsed = urlparse(website_url)
    return f"{parsed.scheme}://{parsed.netloc}"


def _slug(name: str) -> str:
    return "".join(c.lower() if c.isalnum() else "-" for c in name).strip("-") or "agent-server"


def _escape(text: str) -> str:
    return text.replace('"', "'").replace("\n", " ")
